### ISSUE TITLE
Open solution with visual 2015

### ISSUE THREAD

**Issue by TrietPham96** [mvelosop/AspNetCore2CoreUI#1]
Very well, this is what I need, one problem is that when I open the AspNetCore2CoreUI-master solution with visual 2015 then the problem is "The project file can not be loaded"

**Comment by mvelosop** [comment]
Hi @TrietPham96, this solution is an ASP.NET Core 2 and VS 2015 does not support the new .csproj format. Any reason not to use VS 2017?
