### ISSUE TITLE
Upgrade CoreUI

### ISSUE THREAD

**Issue by HakanL** [mvelosop/AspNetCore2CoreUI#2]
Great work, I've been looking for something like this for a while! However it would be great if you could update CoreUI to latest version, there's been some breaking changes, gulpfiles moved, etc. Thanks!

**Comment by mvelosop** [comment]
Hi @HakanL, thanks for the comment!

I'm actually working on it and I've submitted some PRs for v2 for issues I've found while working on the new blog post. One of the PRs, if accepted by @mrholek, is a step in the way to generate Razor views directly from the html files.

I guess you already know https://github.com/coreui/coreui-free-bootstrap-admin-template.

Regards!

**Comment by mvelosop** [comment]
Closing this issue as master branch has already been updated to Core UI 2.0.0

**Comment by mach37** [comment]
can you update to latest
