### ISSUE TITLE
Layout of Index View is broken

### ISSUE THREAD

**Issue by GiorgosBetsos** [mvelosop/AspNetCore2CoreUI#5]
I meticulously followed all steps described in article 'Building elegant applications with ASP.NET Core MVC 2.1 and CoreUI 2'.

A cloned version of the repo that reproduces the issue is [https://github.com/GiorgosBetsos/AspNetCore21CoreUI2](url).

Attached Image with broken layout

![broken layout of index view](https://user-images.githubusercontent.com/18726683/42753004-4208c796-88f8-11e8-9057-1d933f2cc604.png)

**Comment by mvelosop** [comment]
Hi Giorgos,

The Index view broken, the one in your repo is definitely broken, and it's also different from the original repo. I recommend having [Beyond Compare](https://www.scootersoftware.com) or similar in your toolkit, which is great to pinpoint situations like this.

Hope this helps.
